### ISSUE TITLE
Different files for ui.R and server.R

### ISSUE THREAD

**Issue by OmarGonD** [mcpasin/PlayingGoogleAnalyticsDataViz#1]
Thanks for your efforts. I would appreaciate different files for the main part os the dashboard. I want to focus on the "style" part of the code (i guess you haved used some css). 

Gracias por tus esfuerzos. Te agradecería que subieras los códigos por separado, para poder analizar mejor el dashboard, principalmente la parte del estilo.

**Comment by mcpasin** [comment]
Hi, you can find the ui inside the app.R file. It starts with "ui<- ..." 
I actually did not use any custom CSS to make the app, just the main components available in the shinydashboard package. Hope this helps.
