### ISSUE TITLE
Format of the source data?

### ISSUE THREAD

**Issue by TuulaP** [mcpasin/PlayingGoogleAnalyticsDataViz#2]
Hi, Interesting blog post and a script. However, can you tell what is the expected format for  the source data , e.g. file  'DataSources_16Aug.RData ? I read the blog post, but maybe I missed the details.  In the post you mention that you export specific data from Google Analytics as .csv, but in which order, which columns are needed etc.  

(Haven't tried the script yet, it probably contains this info, but it would ease the usage if there would be some explanation of expected formats.)

**Comment by ylleonv** [comment]
I will appreciate to have more information about the data you used

**Comment by nihonjinrxs** [comment]
@mcpasin This repo isn't very useful without the input data format.  We'd love to use the cool stuff you built, but this issue is a blocker.  Can I help you get this up to GitHub?  Happy to document the format for you if you send me the data file (or even a single-row subset for each dataframe).

**Comment by mcpasin** [comment]
Just added the original data source in the repo.

**Comment by nihonjinrxs** [comment]
Excellent.  Thanks, @mcpasin!
